[package]
name = "ros-nalgebra"
version = "0.0.3"
authors = ["Takashi Ogura <ogura@smilerobotics.com>"]
description = "ROS message converter for rosrust and nalgebra"
edition = "2018"
license = "Apache-2.0"
categories = ["algorithms"]
repository = "https://github.com/smilerobotics/ros-nalgebra"
readme = "README.md"

[dependencies]
rosrust = "0.9"
nalgebra = "0.24"
